---
- name: Ansible Playbooks
  hosts: webservers
  become: true
  tasks:

  - name: uninstall apache2 on webservers
    apt:
      name: apache2
      state: absent

  - name: install docker.io on webservers
    apt:
      update_cache: yes
      name: docker.io
      state: present

  - name: install pip3
    apt:
      name: python3-pip
      state: present

  - name: install python docker module
    pip:
      name: docker
      state: present

  - name: download and launch DVWA
    docker_container:
      name: dvwa
      image: cyberxsecurity/dvwa
      state: started
      restart_policy: always
      published_ports: 80:80

  - name: enable docker service
    systemd:
      name: docker
      enabled: yes
